name: Run tests

on: push

jobs:
  build:
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_DB: keystone
          POSTGRES_USER: runner
        ports:
          - 5432:5432
    env:
      SCOPE_DSN: ${{secrets.SCOPE_DSN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Run unit tests
        run: yarn test:unit
